package com.oa.framework.struts;

/**
*Generated by StarUML(tm) Java Add-In
*
*  @ Project : attend_web
*  @ File Name : AbstractAction.java
*  @ Date : 2012/7/3
*  @ Author : 
*/


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts2.ServletActionContext;
import org.apache.struts2.interceptor.ServletRequestAware;

import com.opensymphony.xwork2.ActionContext;
import com.opensymphony.xwork2.ActionSupport;
import com.oa.framework.struts.Page;
import com.oa.framework.struts.Result;

public class AbstractAction extends ActionSupport implements ServletRequestAware {
	protected String namespace = "";
	private HttpServletRequest request; 
	private HttpServletResponse response; 
	protected Page page=new Page();
	protected Result result=new Result<Object>(true);
	protected List list=new ArrayList();
	private String[] title;
	private String[] key;
	private String importAction;

	/**
	 * Get an object from the WebWork user session
	 * @param name
	 * @return java.lang.Object
	 * @roseuid 431F92DB00BD
	 */
	protected Object get(String name) {		
		return ActionContext.getContext().getSession().get(name);
		
	}

	/**
	 * Put an object in the WebWork user session
	 * @param name
	 * @param value
	 * @roseuid 431F92DB00D1
	 */
	protected void set(String name, Object value) {
		ActionContext.getContext().getSession().put(name, value);
	}
	
	public String getActionName(){
		return this.getClass().getName()+"_";
	}
	
	public String getActionNames(){
		return ActionContext.getContext().getActionInvocation().getProxy().getActionName();
	}

	public String getNamespace() {
		return ActionContext.getContext().getActionInvocation().getProxy().getNamespace();
	}
	
	public String getServerLocation() {
		return "HTTP://" + request.getServerName() + ":" + String.valueOf(request.getServerPort());
	}
	
	public String getContextPath(){
		return request.getContextPath();
	}

	public String getHttpPath(){
		return "http:"+"//"+
			getServletRequest().getServerName()+":"+getServletRequest().getServerPort()+
			getServletRequest().getContextPath();
	}

	public void setServletResponse(HttpServletResponse response) {
		this.response=response;
	}
	
	/**
	 * 设置系统属性
	 * <p>作者:lenovo</p>
	 * <p>功能描述:</p>
	 * <p>创建时间:2011May 9, 20115:20:20 PM</p>
	 * <p>@param key
	 * <p>@param value</p>
	 * <p>修改:</p>
	 */
	protected void setGobalAttribute(String key,Object value){
		ActionContext.getContext().getApplication().put(key, value);
	}
	
	/**
	 * 获取系统属性
	 * <p>作者:lenovo</p>
	 * <p>功能描述:</p>
	 * <p>创建时间:2011May 9, 20115:21:54 PM</p>
	 * <p>@param key
	 * <p>@return</p>
	 * <p>修改:</p>
	 */
	protected Object getGobalAttribute(String key){
		return ActionContext.getContext().getApplication().get(key);
	}
	
	public HttpServletResponse getServletResponse(){
		return ServletActionContext.getResponse();
	}
	public void setServletRequest(HttpServletRequest request) {
		this.request=request;
	}
	
	public HttpServletRequest getServletRequest(){
		return request;
	}

	public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	public Result getResult() {
		//设置国际化消息
		if(result!=null){
			if (result.getCodeParams() != null && result.getCodeParams().length > 0) {
				try {
					List paramList = Arrays.asList(result.getCodeParams());
					result.setMessage(getText(result.getCode(),paramList));
				} catch (Exception ex) {
					ex.printStackTrace();
				}
			} else {
				result.setMessage(getText(result.getCode()));
			}
		}
		return result;
	}

	protected void clear()
	{
		ActionContext.getContext().getSession().clear();
	}
	
	public void setResult(Result result) {
		this.result = result;
	}

	public List getList() {
		return list;
	}

	public String[] getTitle() {
		return title;
	}

	public void setTitle(String[] title) {
		this.title = title[0].split(",");
	}

	public String[] getKey() {
		return key;
	}

	public void setKey(String[] key) {
		this.key = key[0].split(",");
	}

	public String getImportAction() {
		return importAction;
	}

	public void setImportAction(String importAction) {
		this.importAction = importAction;
	}
	
	
}
